import React, { PropsWithChildren } from "react";
import { AdminNavbar } from "@/components/navigation";
import { Footer } from "@/components/Footer";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <div className="flex flex-col lg:flex-row h-screen w-screen max-w-full overflow-hidden">
      <AdminNavbar />
      <Separator orientation="vertical" className="hidden lg:block" />
      <main className="grow flex flex-col justify-between overflow-hidden  overflow-y-scroll   bg-muted">
        {children}
        <Footer />
      </main>
    </div>
  );
}
